### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by Liuba8** [DriesLanduyt/PMAT#3]
[Try2.zip](https://github.com/DriesLanduyt/PMAT/files/96120/Try2.zip)

Hallo!
I`m currently using your plug-in for the project in uni and so far I met some problems. When I run the plug-in (even example which you provided) I get the run error "the input and output nodesets are not defined correctly". My Netica model consists of 2 input nodes (precipitation and soil type) and 1 output node (flood source). I will add more nodes, now I`m just trying to run very simple one. values are taken from attribute table and personal csv tables are created. I attached all files. I would be very thankful if you can tell me what is wrong.

**Comment by DriesLanduyt** [comment]
What version of QGIS and Netica you're working with?  And can you provide me the BBN model you're using (was not in the zip file)? As the error suggests there can be something wrong with the way you defined your nodesets in Netica.

**Comment by Liuba8** [comment]
Hi,DriesLanduyt! I already found my mistakes, this is exactly what you said!So far everything works! Thanks for you answer and for your research in this field! It helps me a lot with my current project and future master thesis!
