### ISSUE TITLE
titles of outputnode’s stastes should be defined numerically

### ISSUE THREAD

**Issue by zyl199282** [DriesLanduyt/PMAT#7]
Hello!When  I was putting my files into PMAT,I had a problem,the software would pop up a message

![image 4](https://cloud.githubusercontent.com/assets/27752972/26670887/14a1f5c0-46e6-11e7-9bc2-1df4c18fe5e6.png)

![image 6](https://cloud.githubusercontent.com/assets/27752972/26671080/d1aa379a-46e6-11e7-8946-561474564577.png)

**Comment by zyl199282** [comment]
but  I had set the node of NDVI as outputnode,I can‘t find the reason,I hope  my problem can solve，thank  you very much!
![image 7](https://cloud.githubusercontent.com/assets/27752972/26671233/4d8eccb8-46e7-11e7-865c-573446aca194.png)

**Comment by DriesLanduyt** [comment]
This error message refers to the obligation that you have to define the titles of the states numerically (not as strings). Normally, you can just use the numbers you set as state values.
